GRANT USAGE ON DATABASE HELLO_WORLD_DB TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA HELLO_WORLD_DB.DEMO_SCHEMA TO ROLE SYSADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA HELLO_WORLD_DB.DEMO_SCHEMA TO ROLE SYSADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA HELLO_WORLD_DB.DEMO_SCHEMA TO ROLE SYSADMIN;