-- Create database
CREATE DATABASE IF NOT EXISTS HELLO_WORLD_DB;

-- Create schema
CREATE SCHEMA IF NOT EXISTS HELLO_WORLD_DB.DEMO_SCHEMA WITH MANAGED ACCESS;

-- Create table
CREATE TABLE IF NOT EXISTS HELLO_WORLD_DB.DEMO_SCHEMA.HELLO_WORLD (
    FIRST_NAME VARCHAR(100),
    LAST_NAME  VARCHAR(100)
);
